[package]
name = "mft"
version = "0.0.1"
edition = "2024"
authors = [
    "Ryan Doughty <rdd4@rice.edu>",
    "Todd Treangen <treangen@rice.edu>",
]
license = "MIT"
description = "Min-Frame Transformation for sequence analysis"
readme = "README.md"
keywords = ["genome alignment", "seeding", "MUMs", "kmers"]
categories = ["command-line-utilities", "science"]
repository = "https://github.com/treangenlab/MFT"

[dependencies]
needletail = "0.6.0"
clap = { version = "4", features = ["derive"] }
rustc-hash = "2.1.1"
simple_logger = "5.2.0"
log = "0.4.29"
itertools = "0.14.0"
rand = "0.10.1"
